### ISSUE TITLE
WireMock 3.6.0 support

### ISSUE THREAD

**Issue by picimako** [picimako/wiremocha#104]
### Summary

Add support for the new features and changes in WireMock 3.6.0:
- https://www.wiremock.io/post/wiremock-3-6-0-released
- https://github.com/wiremock/wiremock/releases/tag/3.6.0

### Tasks
- [x] [`arrayJoin` Handlebars helper](https://wiremock.org/docs/response-templating/#arrayjoin-helper)
  - It can be used as a block helper.
  - At least two parameters must be specified: the separator and the array of elements to concatenate.
  - It supports the following, optional hashes:
    - `prefix`: added to the beginning of the result
    - `suffix`: added to the end of the result
  - FQN of helper implementation: `com.github.tomakehurst.wiremock.extension.responsetemplating.helpers.JoinHelper`
- [x] [`arrayAdd` Handlebars helper](https://wiremock.org/docs/response-templating/#array-add--remove-helpers):
  - It cannot be used as a block helper.
  - Exactly two parameters must be specified: the array to which addition happens, and the value to be added.
  - It supports the following, optional hashes:
    - `position`: its value is either a positive, 0-based index, or the `start` or `end` keywords. If not specified, `end` is the default value.
  - FQN of helper implementation: `com.github.tomakehurst.wiremock.extension.responsetemplating.helpers.ArrayAddHelper`
- [x] [`arrayRemove` Handlebars helper](https://wiremock.org/docs/response-templating/#array-add--remove-helpers):
  - It cannot be used as a block helper.
  - Exactly one parameter must be specified: the array from which to remove an item
  - It supports the following, optional hashes:
    - `position`: its value is either a positive, 0-based index, or the `start` or `end` keywords. If not specified, `end` is the default value.
  - FQN of helper implementation: `com.github.tomakehurst.wiremock.extension.responsetemplating.helpers.ArrayRemoveHelper`
- [x] [`val` Handlebars helper](https://wiremock.org/docs/response-templating/#val-helper):
  - It cannot be used as a block helper.
  - Exactly one parameter must be specified: the variable name to access, or the value to assign to a variable.
  - It supports the following, optional hashes:
    - `or`: the default, fallback value. Same as `default`.
    - `default`: the default, fallback value. Same as `or`.
    - `assign`: the variable name to assign the value to
  - FQN of helper implementation: `com.github.tomakehurst.wiremock.extension.responsetemplating.helpers.ValHelper`
- [x] New `supported-proxy-encodings` CLI argument (https://github.com/wiremock/wiremock/pull/2694).

**Comment by picimako** [comment]
Completed in v1.0.28.
