### ISSUE TITLE
WireMock 3.7.0 and 3.8.0 support

### ISSUE THREAD

**Issue by picimako** [picimako/wiremocha#107]
### Summary

Support for the WireMock 3.7.0 and 3.8.0.

### Tasks for 3.7.0
- [x] Update wiremock-state-extension to v0.8.0
- [x] https://github.com/wiremock/wiremock/pull/2747: `ignoreOrderOfSameNode` property
  - [x] Add it to the Java stub mapping preview.
  - [x] Add it to the stub mapping and StringValuePattern schemas.
  - [x] Mark the property as 'since 3.7.0' in the property description in the schemas.
  - [x] Any other locations to support?
- [x] https://github.com/wiremock/wiremock/pull/2757
  - [x] Code completion of the request id in the webook `originalRequest` property in Handlebars helpers.
    - !! Check the documentation to make sure this is correct.
- [x] https://github.com/wiremock/wiremock/pull/2733
  - [x] Default argument value for `WireMockConfiguration.preserveUserAgentProxyHeader()`.
  - [x] Add `preserve-user-agent-proxy-header` CLI option to Testcontainers code completion.
- [x] https://github.com/wiremock/wiremock/pull/2752
  - [x] Default argument value for `WireMockConfiguration.withMaxTemplateCacheEntries()`.
  - [x] Inlay hint for passing `null` into `WireMockConfiguration.withMaxTemplateCacheEntries()` meaning there is no limit (infinite) on the number cache entries.
  - [ ] ?? Should an inspection (maybe with warning level) be created to signal passing in null to `withMaxTemplateCacheEntries()`?
- [x] https://github.com/wiremock/wiremock/pull/2743
  - [ ] Add support for the new endpoint in the Admin API Client tool window.
    - This will be handled in https://github.com/picimako/wiremocha/issues/108.
- [x] https://github.com/wiremock/wiremock/pull/2744
  - [x] Default argument values for `WireMockConfiguration.maxHttpClientConnections()` and `WireMockConfiguration.disableConnectionReuse()`.
  - [x] Add `max-http-client-connections` and `disable-connection-reuse` CLI options to Testcontainers code completion.
- [x] https://github.com/wiremock/wiremock/pull/2742
  - [x] Check this in the Admin API tool window, and handle it if necessary.
- [ ] https://github.com/wiremock/wiremock/pull/2769
  - [x] Mark `max-proxy-http-client-connections` and `disable-proxy-client-connection-reuse` CLI options as 'until 3.6.0'.
  - [x] Add `max-http-client-connections` and `disable-connection-reuse` CLI options as 'since 3.7.0'.
  - [ ] ?? May be an inspection could be useful to report the already used CLI options as unavailable if the current WireMock version is not in the supported version range.

### Tasks for 3.8.0
- [x] https://github.com/wiremock/wiremock/pull/2782
  - [x] Potential request attribute code completion.

### Resources
- https://www.wiremock.io/post/wiremock-3-7-0-released
- https://github.com/wiremock/wiremock/releases/tag/3.7.0
- https://www.wiremock.io/post/wiremock-3-8-0-released
- https://github.com/wiremock/wiremock/releases/tag/3.8.0

**Comment by picimako** [comment]
Completed in v1.0.29.
