### ISSUE TITLE
Integrate various parts of projects with the Admin API tool window

### ISSUE THREAD

**Issue by picimako** [picimako/wiremocha#113]
### Summary

As many endpoints in the Admin API work with JSON stub mappings, it could be beneficial to integrate actual stub mapping files with the Admin API tool window.

### Tasks
- [ ] Context menu action in the Project View to create/update a mapping based on the selected JSON stub mapping file, or a given stub mapping in it, if multi-mapping.
- [ ] Floating action bar button to create/update a mapping based on the selected JSON stub mapping file, or a given stub mapping in it, if multi-mapping.
- [ ] Create JSON stub mapping(s) in the project from endpoint responses containing stub mappings.
  -  This could be a button on the response body side in the tool window.
