### ISSUE TITLE
Support based64 body conversion with concatenated strings and Java text blocks 

### ISSUE THREAD

**Issue by picimako** [picimako/wiremocha#40]
## Summary

The intention action that converts `withBody(String)` calls to `withBase64Body(String)` calls now supports only single String instances.

## Tasks
- [x] Extend the intention to support conversion when the argument consists of multiple concatenated strings, e.g.
```
withBody("{\n" +
"  \"property\": {\n" +
"    \"someKey\": \"someValue\"\n" +
"  }\n" +
"}")
```
  - This will be supported only when all parts of the concatenation is a String literal, character literal, or a String constant that can be evaluated.

- [x] Extend the intention to support text blocks, e.g.
```
withBody(
"""{
  "property": {
    "someKey": "someValue"
  }
}""")
```

- [x] Explore and collect other WireMocha features that could be improved the same way.

**Comment by picimako** [comment]
Completed in v1.0.9.
