### ISSUE TITLE
Investigate and add support for URL path template variables

### ISSUE THREAD

**Issue by picimako** [picimako/wiremocha#43]
### Summary

WireMock 3.0.0-beta3 introduced support for URL path template variable:
- https://github.com/wiremock/wiremock/releases/tag/3.0.0-beta-3
- https://github.com/wiremock/wiremock.org-sources/blob/3.0.0-beta/_docs/request-matching.md#path-templates

### Tasks
- Collect what kind of support can be added for this feature.

### Feature candidates
- [x] Update JSON schema of stub mappings to include all properties for the path templates.
  - Double-check beforehand, if the schemas in WireMock are also updated.
- [x] Update duplicate URL property and call checker to include `urlPathTemplate` and `urlPathTemplate()`.
- [x] Inspection to report when the `pathParameters` property is specified but `urlPathTemplate` is not.
- [x] Intention action to add `urlPathTemplate` property in JSON, and `withPathParam()` in Java DSL for all not configured path template variables.
  - [x] JSON DSL
  - [x] Java DSL
- [x] Inspection to report the `urlPathTemplate` / `urlPathTemplate()` value if there is no path parameter in it.
  - [x] JSON DSL
  - [x] Java DSL
- [x] Inspection to report if a path param in `pathParameters` is not a path variable in `urlPathTemplate`
  - [x] JSON DSL
  - [x] Java DSL

**Comment by picimako** [comment]
Completed in v1.0.9.
