### ISSUE TITLE
Add support for WireMock 3.0.0-beta5

### ISSUE THREAD

**Issue by picimako** [picimako/wiremocha#45]
### Summary

WireMock 3.0.0-beta5 is available at https://github.com/wiremock/wiremock/releases/tag/3.0.0-beta-5. Make sure to add support for those changes.

### Tasks
- [x] Default value validation for `proxyTimeout`: https://github.com/wiremock/wiremock/pull/2058
- [x] Default value validation for `proxyPassThrough` in https://github.com/wiremock/wiremock/pull/2087
- [x] `request.clientIP` attribute in response templating: https://github.com/wiremock/wiremock/pull/2103
  - Add completion for `clientIp`.
  - Adjust code completion in general for `request`.

**Comment by picimako** [comment]
Completed in v1.0.9.
