### ISSUE TITLE
Investigate support for webhooks

### ISSUE THREAD

**Issue by picimako** [picimako/wiremocha#69]
### Summary

Webhooks is an area of WireMock that hasn't been touched by WireMocha.

### Tasks
- Investigate potential support for webhooks.

### Ideas
- ~~Default argument reporting for methods in the `webhook()` chain~~.
- [x] Include webhook serveEventListeners in the JSON-to-Java stub preview.
- [x] Code completion of the `originalRequest` Handlebars variable, and its sub-properties.
  - Add a tooltip or type text to this, that it can be used only in webhooks.
- [x] Handlebars language injection into webook serveEventListeners.
  - Does the serveEventListener name value identify the type of listeners that is used in it, or is it just a simple name?
  - URL, method and body are sure to accept Handlebars helpers. Any other property?
- [x] Content type header code completion in `webhook().withHeader("Content-Type", "<caret>")`.
  - [x] Java DSL
  - [x] JSON DSL
- [x] Is any method in `WebhookDefinition` mandatory in order for the webhook to work properly? Other Java side checks?
  - [x] `withUrl()` method
  - [x] Is ANY request method supported for webhooks?
  - [x] webhook definition used with non-*webhook* name.
  - [x] Either `withBody()`or `withBinaryBody()` maybe be specified, but not both.
- [x] JSON DSL code analysis
  - [x] `url` property is missing 
  - [x] Is ANY request method supported for webhooks?
  - [x] the `headers` property must be a map (an object), and not an array or something else.
  - [x] Either `body` or `base64Body` may be specified, but not both.

### Not implementing for now
- Intention action to convert webhook() call chains to `WebhookTransformer` extension implementation. Is it possible to make such a conversion?
  - This could be useful when one wants to provide custom logic for the webhooks. 
-  Inspection: *Webhook templates currently do not support system or environment variables.*
  - This might be obsolete, but have to check. See `systemValue` Handlebars helper.

### Resources
- https://wiremock.org/3.x/docs/webhooks-and-callbacks/
- https://github.com/wiremock/wiremock/pull/2307
