### ISSUE TITLE
Code completion for `truncateDate` helper truncation values

### ISSUE THREAD

**Issue by picimako** [picimako/wiremocha#77]
### Summary

One of the `truncateDate` helper's parameters is the truncation itself that has a few possible values.

### Tasks
- [x] Extend Handlebars code completion to complete the truncation too.
- [x] This could include an inspection too, to validate truncation values.
- [x] Also a reference to the appropriate enum constant in `DateTimeTruncation`

### Documentation
- https://wiremock.org/docs/response-templating/#date-and-time-helpers
- https://wiremock.org/docs/request-matching/#all-truncations

**Comment by picimako** [comment]
Completed in v1.0.20.
