### ISSUE TITLE
Add support for wiremock-faker-extension

### ISSUE THREAD

**Issue by picimako** [picimako/wiremocha#81]
### Summary

There is a new WireMock extension being introduced for Faker: https://github.com/wiremock/wiremock-faker-extension

Investigate and add inspections, code completion, etc. for the new Handlebars helper.

### Tasks
- [x] Add validation for the number of parameters to be exactly 1.
- [x] Add validation so that the faker expression must not be wrapped in `#{` and `}`.
- [x] Add reference contributor for the helper name, so that users can navigate to its implementation class, and so that it is included in reference searches.

### Resources
- https://github.com/datafaker-net/datafaker
- https://www.wiremock.io/post/wiremock-3-goes-ga

**Comment by picimako** [comment]
Completed in v1.0.22.
