### ISSUE TITLE
Add support for WireMock 3.4.0

### ISSUE THREAD

**Issue by picimako** [picimako/wiremocha#86]
### Summary

[WireMock 3.4.0](https://github.com/wiremock/wiremock/releases/tag/3.4.0) has recently been released. Collect and implement necessary updates for this release.

### Tasks
- [x] https://github.com/wiremock/wiremock/pull/2500
  - Extend the availability criteria of the intentions of converting JUnit5 tests from programmatic to declarative and vice versa with checking the `@WireMockTest` annotation in base classes too.
- [x] https://github.com/wiremock/wiremock/pull/2509
  - Simply make sure that the JSON stub mapping preview, and any other related feature works properly.
- [x] https://github.com/wiremock/wiremock/pull/2453
  - Add the `version` to the WireMock testcontainers Java CLI options code completion.
- [x] https://github.com/wiremock/wiremock/pull/2561
  - Support `extensionScanningEnabled` in intentions converting JUnit5 tests from programmatic to declarative and vice versa.
- https://github.com/wiremock/wiremock/pull/2555
  - [x] Add support for the new request method in the JSON stub mapping preview.
  - [x] Make sure that the new request method becomes available in the scenario generation tool window as well.

**Comment by picimako** [comment]
Completed in v1.0.22.
