### ISSUE TITLE
Support for WireMock 3.5.0 - 3.5.2

### ISSUE THREAD

**Issue by picimako** [picimako/wiremocha#95]
### Summary

WireMock 3.5.0, 3.5.1 and 3.5.2 have been released, let's support them.

### Tasks
- [3.5.0](https://github.com/wiremock/wiremock/releases/tag/3.5.0)
  - https://github.com/wiremock/wiremock/pull/2653
    - [x] Add code completion for the following Testcontainers WireMock CLI options: `disable-http2-plain`, `disable-http2-tls"`
  - https://github.com/wiremock/wiremock/pull/2644
    - [x] Update stub mapping JSON schema with the new `removeProxyRequestHeaders` property.
    - [x] Make sure that the new `removeProxyRequestHeaders` setting works properly for the Java stub mapping preview.
  - https://github.com/wiremock/wiremock/pull/2630
    - [x] Add the `default` hash for the `systemValue` Handlebars helper. It should at least be marked as *Since WireMock 3.5.0*.
